New Methods for Worksheet: InsertRow, FirstCellByValue, FirstOrDefaul…
rabanti-github/NanoXLSX pull request #72
Opened 2024-12-31 15:48 UTC by BombusSoftware

New Methods for Worksheet: 

InsertRow
FirstCellByValue
FirstOrDefaultCell,
CellsByValue
ReplaceCellValue

See Issue #71 for more explanation.

I had to change the target framework from .net5 to .net8 because my computer no longer has .net5 installed...

2025-01-03 22:41 UTC, rabanti-github requested changes
There are two things that probably should be handled.
There are functions that are looking up cells by value, but ignoring empty cells, where the value is null. Then there is a framework upgrade that should be avoided, if possible.
Some other minor, not very urgent, things are mentioned in the comments.

2025-01-03 22:41 UTC, rabanti-github commented on NanoXLSX/Worksheet.cs
> +        public List<Cell> CellsByValue(object searchValue)
Here, it is not possible to get a list of empty cells, where the value is null (could be a useful function IMHO). This is also the cause of the previously described, possible bug.

The same applies also to the function `public Cell FirstCellByValue(object searchValue)` on line 2694

2025-01-05 09:38 UTC, BombusSoftware commented on NanoXLSX/Worksheet.cs
> +                for (Int32 i = 0; i < numberOfNewRows; i++)
I don't know what I was thinking :)

2025-01-05 09:46 UTC, BombusSoftware commented on NanoXLSX/Worksheet.cs
> +                    Cell newCell = new Cell("", Cell.CellType.EMPTY, newAddress);
Ah yes, that makes sense! I've changed it.

2025-01-05 09:48 UTC, BombusSoftware commented on NanoXlsx Test/NanoXLSX Test.csproj
> +    <TargetFramework>net8.0</TargetFramework>
I no longer have .net5 on my computer, so the tests are not running. Temporarily I tried it with .net8. I forgot to change it back to .net5 here.
But I understand your approach.

2025-01-05 09:49 UTC, BombusSoftware commented on NanoXLSX/Worksheet.cs
> +            List<Cell> foundCells = this.CellsByValue(oldValue);
That's right! This is related to the above filter (!= null) and should now work. I have extended the test a little.

2025-01-05 09:51 UTC, BombusSoftware commented on NanoXlsx Test/Worksheets/WorksheetTest.cs
> +        #region Tests f�r Insert-Search-Replace
I have not changed the encoding, strange that it does not display the character correctly. But since it doesn't belong here anyway, I “translated” it.

2025-01-05 09:56 UTC, BombusSoftware commented
I think I have implemented all your suggested changes. Thanks for your code review!
Es hat gar nicht weh getan ;)  (It didn't hurt!)

I made a new commit with the changes and I think the PR is updated automatically?

If there is anything else I can or should do, please let me know!

This marks the start of 2025 for me with my very first pull request and my first contribution to an open source project. 
That makes me want to do more ;)
I wish you and everyone who uses nanoXLSX a Happy New Year!

2025-01-10 20:55 UTC, rabanti-github approved these changes
Looks good!
Happy new year too! Sorry about the delay. Was a little bit a tough week.
I will add some parametrized unit tests and will also do some code maintenance in the project, before I release the new version.
Thank you very much for the contribution.

2025-01-10 20:56 UTC, merged